/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/matters/{matter_id}/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_api_matters__matter_id__ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matters/{matter_id}/locate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Locate */
        post: operations["locate_api_matters__matter_id__locate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matters/{matter_id}/provider-draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Provider Draft */
        post: operations["provider_draft_api_matters__matter_id__provider_draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/invite/{code}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Invite */
        post: operations["accept_invite_api_auth_invite__code__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matters/{matter_id}/brief": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Brief */
        get: operations["brief_api_matters__matter_id__brief_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matters/{matter_id}/visits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Visit */
        post: operations["visit_api_matters__matter_id__visits_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matters/{matter_id}/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Changes */
        get: operations["changes_api_matters__matter_id__changes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matters/{matter_id}/delta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Delta */
        get: operations["delta_api_matters__matter_id__delta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matters/{matter_id}/suggested-questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Suggested Questions */
        get: operations["suggested_questions_api_matters__matter_id__suggested_questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai-costs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Matter Costs */
        get: operations["matter_costs_api_ai_costs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai-costs/firm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Firm Costs */
        get: operations["firm_costs_api_ai_costs_firm_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/digest/{matter_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Digest */
        post: operations["run_digest_api_digest__matter_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matters/{matter_id}/digest-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Digest Runs */
        get: operations["digest_runs_api_matters__matter_id__digest_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Matters */
        get: operations["list_matters_api_matters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matters/{matter_id}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_matters__matter_id__overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matters/{matter_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Timeline */
        get: operations["timeline_api_matters__matter_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matters/{matter_id}/deadlines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Deadlines */
        get: operations["deadlines_api_matters__matter_id__deadlines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matters/{matter_id}/costs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Costs */
        get: operations["costs_api_matters__matter_id__costs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matters/{matter_id}/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Providers */
        get: operations["providers_api_matters__matter_id__providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/provider/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Cases */
        get: operations["my_cases_api_provider_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/provider/cases/{grant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Case */
        get: operations["my_case_api_provider_cases__grant_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/provider/cases/{grant_id}/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Document */
        get: operations["my_document_api_provider_cases__grant_id__documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/provider/requests/{request_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Request */
        post: operations["complete_request_api_provider_requests__request_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/records/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Record */
        get: operations["get_record_api_records__record_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/pages/{page_no}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Page */
        get: operations["get_page_api_documents__document_id__pages__page_no__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/pages/{page_no}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Page Image */
        get: operations["get_page_image_api_documents__document_id__pages__page_no__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get File */
        get: operations["get_file_api_documents__document_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matters/{matter_id}/share-candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Share Candidates */
        get: operations["share_candidates_api_matters__matter_id__share_candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matters/{matter_id}/shares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Grants */
        get: operations["list_grants_api_matters__matter_id__shares_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Grant */
        post: operations["create_grant_api_shares_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shares/{grant_id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Release */
        post: operations["release_api_shares__grant_id__release_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shares/{grant_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke */
        post: operations["revoke_api_shares__grant_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shares/{grant_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit */
        get: operations["audit_api_shares__grant_id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requests/{request_id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dismiss Request */
        post: operations["dismiss_request_api_requests__request_id__dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/clio/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clio Login */
        get: operations["clio_login_auth_clio_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/clio/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clio Callback */
        get: operations["clio_callback_auth_clio_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/{matter_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Matter */
        post: operations["sync_matter_api_sync__matter_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sync Status */
        get: operations["sync_status_api_sync_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Adherence */
        Adherence: {
            /**
             * Visits
             * @description ISO dates of recorded visits
             */
            visits: string[];
            /**
             * Gaps
             * @description [{from, to, days}] gaps over the threshold
             */
            gaps?: {
                [key: string]: unknown;
            }[];
            /** Current Gap Days */
            current_gap_days?: number | null;
        };
        /** AiCostReport */
        AiCostReport: {
            /** Matter Id */
            matter_id: number | null;
            /** Total Usd */
            total_usd: number;
            /** One Time Usd */
            one_time_usd: number;
            /** Ongoing Usd */
            ongoing_usd: number;
            /** Ask Count */
            ask_count: number;
            /** Avg Ask Usd */
            avg_ask_usd: number;
            /** Cache Savings Usd */
            cache_savings_usd: number;
            /** By Purpose */
            by_purpose: components["schemas"]["PurposeCost"][];
            /** By Model */
            by_model: components["schemas"]["PurposeCost"][];
            /** Series */
            series: components["schemas"]["DayCost"][];
            /** Budget Usd */
            budget_usd?: number | null;
            /** Budget Pct */
            budget_pct?: number | null;
            /** Runs */
            runs: components["schemas"]["AiRun"][];
        };
        /** AiRun */
        AiRun: {
            /** At */
            at: string;
            /** User */
            user?: string | null;
            /** Purpose */
            purpose: string;
            /** Model */
            model: string;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Cost Usd */
            cost_usd: number;
            /**
             * Cache Hit
             * @default false
             */
            cache_hit: boolean;
        };
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
            /** History */
            history?: components["schemas"]["AskTurn"][];
        };
        /** AskTurn */
        AskTurn: {
            /** Question */
            question: string;
            /** Answer Text */
            answer_text: string;
        };
        /** Assumption */
        Assumption: {
            /**
             * Label
             * @description "Bills total" | "Injury severity" | "Policy limits" | ...
             */
            label: string;
            /** Text */
            text: string;
            /**
             * Not Found
             * @default false
             */
            not_found: boolean;
            /** Citations */
            citations?: components["schemas"]["Citation"][];
        };
        /** BillLine */
        BillLine: {
            /** Date */
            date?: string | null;
            /** Amount */
            amount: number;
            /** Description */
            description?: string | null;
        };
        /** Brief */
        Brief: {
            /** Matter Id */
            matter_id: number;
            /** Story */
            story: components["schemas"]["CitedSentence"][];
            /** Key Moments */
            key_moments: components["schemas"]["KeyMoment"][];
            /** Total Records */
            total_records: number;
            /** Injuries */
            injuries: components["schemas"]["Injury"][];
            /** Worth */
            worth: components["schemas"]["WorthEstimate"] | components["schemas"]["NotFound"];
            coverage: components["schemas"]["Coverage"];
            /** Waiting On */
            waiting_on: components["schemas"]["DeadlineItem"][];
            /** Last Client Contact */
            last_client_contact: components["schemas"]["Cited_ClientContact_"] | components["schemas"]["NotFound"];
            /** Digested At */
            digested_at?: string | null;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            /**
             * Stale
             * @description True if records changed since the last digest run
             */
            stale: boolean;
        };
        /** CaseValueShare */
        CaseValueShare: {
            /**
             * Label
             * @default Estimate
             * @constant
             */
            label: "Estimate";
            /** Low */
            low: number;
            /** High */
            high: number;
        };
        /** ChangeItem */
        ChangeItem: {
            /** Record Id */
            record_id: string;
            /**
             * Change
             * @enum {string}
             */
            change: "new" | "changed" | "removed";
            /**
             * Type
             * @enum {string}
             */
            type: "note" | "communication" | "task" | "calendar_entry" | "document" | "expense" | "time_entry" | "bill" | "medical_record" | "medical_bill" | "damage" | "custom_field" | "matter_event" | "contact";
            /** Title */
            title: string;
            /** Occurred At */
            occurred_at?: string | null;
            /** Importance */
            importance?: number | null;
            /** Why It Matters */
            why_it_matters?: string | null;
            /** Citations */
            citations: components["schemas"]["Citation"][];
        };
        /** Changes */
        Changes: {
            /** Since */
            since: string | null;
            /** First Visit */
            first_visit: boolean;
            /** Items */
            items: components["schemas"]["ChangeItem"][];
            /**
             * Empty Message
             * @description Set when nothing changed: "Nothing has changed since..."
             */
            empty_message?: string | null;
            last_activity?: components["schemas"]["LastActivity"] | null;
        };
        /** Citation */
        Citation: {
            /**
             * Record Id
             * @description Our record id, e.g. "note:123" or "document:456"
             */
            record_id: string;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "note" | "communication" | "task" | "calendar_entry" | "document" | "expense" | "time_entry" | "bill" | "medical_record" | "medical_bill" | "damage" | "custom_field" | "matter_event" | "contact";
            /** Title */
            title: string;
            /** Author */
            author?: string | null;
            /**
             * Date
             * @description ISO date/time of the source item
             */
            date?: string | null;
            /**
             * Page
             * @description 1-based page for document citations
             */
            page?: number | null;
            /**
             * Char Start
             * @description Offset into the source text (record body_text, or the page text when page is set)
             */
            char_start: number;
            /** Char End */
            char_end: number;
            /**
             * Excerpt
             * @description The exact cited source text
             */
            excerpt: string;
            /** Clio Url */
            clio_url?: string | null;
        };
        /** CitedSentence */
        CitedSentence: {
            /** Text */
            text: string;
            /** Citations */
            citations: components["schemas"]["Citation"][];
        };
        /** Cited[ClientContact] */
        Cited_ClientContact_: {
            value: components["schemas"]["ClientContact"];
            /** Citations */
            citations: components["schemas"]["Citation"][];
        };
        /** Cited[float] */
        Cited_float_: {
            /** Value */
            value: number;
            /** Citations */
            citations: components["schemas"]["Citation"][];
        };
        /** Cited[str] */
        Cited_str_: {
            /** Value */
            value: string;
            /** Citations */
            citations: components["schemas"]["Citation"][];
        };
        /** ClientContact */
        ClientContact: {
            /** At */
            at: string;
            /** Days Ago */
            days_ago: number;
            /**
             * Channel
             * @description email | call | note | meeting | text | other
             */
            channel: string;
            /** By */
            by?: string | null;
            /** Summary */
            summary?: string | null;
        };
        /** ClientInfo */
        ClientInfo: {
            /** Contact Id */
            contact_id?: number | null;
            /** Name */
            name: string;
            /**
             * Photo Url
             * @description API URL serving the photo, if one was found
             */
            photo_url?: string | null;
            photo_citation?: components["schemas"]["Citation"] | null;
            /** Date Of Birth */
            date_of_birth?: components["schemas"]["Cited_str_"] | components["schemas"]["NotFound"] | null;
            /** Age */
            age?: number | null;
            /** Phone */
            phone?: string | null;
            /** Email */
            email?: string | null;
        };
        /** CostCategory */
        CostCategory: {
            /** Category */
            category: string;
            /** Amount */
            amount: number;
            /** Count */
            count: number;
            /** Citations */
            citations: components["schemas"]["Citation"][];
        };
        /** Costs */
        Costs: {
            /** Total */
            total: components["schemas"]["Cited_float_"] | components["schemas"]["NotFound"];
            /** By Category */
            by_category: components["schemas"]["CostCategory"][];
            /** Monthly */
            monthly: components["schemas"]["MonthAmount"][];
        };
        /** Coverage */
        Coverage: {
            /** Carrier */
            carrier: components["schemas"]["Cited_str_"] | components["schemas"]["NotFound"];
            /** Bi Per Person */
            bi_per_person: components["schemas"]["Cited_str_"] | components["schemas"]["NotFound"];
            /** Bi Per Accident */
            bi_per_accident: components["schemas"]["Cited_str_"] | components["schemas"]["NotFound"];
            /** Um Uim */
            um_uim: components["schemas"]["Cited_str_"] | components["schemas"]["NotFound"];
            /** Medpay */
            medpay: components["schemas"]["Cited_str_"] | components["schemas"]["NotFound"];
            /**
             * Confirmed
             * @description True if any liability coverage fact was found
             */
            confirmed: boolean;
        };
        /** CoverageShare */
        CoverageShare: {
            /** Confirmed */
            confirmed: boolean;
            /** Carrier */
            carrier?: string | null;
            /**
             * Limits Text
             * @description Only when coverage_detail == "limits"
             */
            limits_text?: string | null;
        };
        /** CreateGrantRequest */
        CreateGrantRequest: {
            /** Matter Id */
            matter_id: number;
            /** Provider Contact Id */
            provider_contact_id: number;
            /** Email */
            email: string;
        };
        /** DayCost */
        DayCost: {
            /** Date */
            date: string;
            /** Usd */
            usd: number;
        };
        /** DeadlineItem */
        DeadlineItem: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "task" | "calendar" | "sol" | "waiting_on";
            /** Due At */
            due_at?: string | null;
            /** Status */
            status?: string | null;
            /** Assignee */
            assignee?: string | null;
            /** Waiting On */
            waiting_on?: string | null;
            /**
             * Overdue
             * @default false
             */
            overdue: boolean;
            /** Citations */
            citations: components["schemas"]["Citation"][];
        };
        /** Deadlines */
        Deadlines: {
            /** Overdue */
            overdue: components["schemas"]["DeadlineItem"][];
            /** Upcoming */
            upcoming: components["schemas"]["DeadlineItem"][];
            /** Waiting On */
            waiting_on: components["schemas"]["DeadlineItem"][];
        };
        /** Delta */
        Delta: {
            /** Since */
            since: string | null;
            /** Summary */
            summary: components["schemas"]["CitedSentence"][];
            /** Cached */
            cached: boolean;
        };
        /** DigestRun */
        DigestRun: {
            /** Id */
            id: number;
            /** Matter Id */
            matter_id: number;
            /** Trigger */
            trigger: string;
            /** Started At */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Records Seen */
            records_seen: number;
            /** Records Changed */
            records_changed: number;
            /** Llm Calls */
            llm_calls: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Cost Usd */
            cost_usd: number;
            /** Cache Hit */
            cache_hit: boolean;
            /** Stages */
            stages?: {
                [key: string]: unknown;
            };
        };
        /** DocumentPage */
        DocumentPage: {
            /** Document Id */
            document_id: string;
            /** Page No */
            page_no: number;
            /** Page Count */
            page_count: number;
            /** Text */
            text: string;
            /**
             * Method
             * @enum {string}
             */
            method: "text_layer" | "ocr" | "none" | "pending";
            /** Image Url */
            image_url?: string | null;
        };
        /** DraftFlag */
        DraftFlag: {
            /** Text */
            text: string;
            /** Reason */
            reason: string;
        };
        /** FirmCostReport */
        FirmCostReport: {
            /** Matters */
            matters: components["schemas"]["MatterCost"][];
            /** Series */
            series: components["schemas"]["DayCost"][];
            /** Total Usd */
            total_usd: number;
        };
        /** Grant */
        Grant: {
            /** Id */
            id: number;
            /** Matter Id */
            matter_id: number;
            /** Provider Contact Id */
            provider_contact_id: number;
            /** Provider Name */
            provider_name?: string | null;
            /** Email */
            email: string;
            /** Provider User Id */
            provider_user_id?: number | null;
            /** Latest Version */
            latest_version?: number | null;
            /** Released At */
            released_at?: string | null;
            /** Revoked At */
            revoked_at?: string | null;
            /** Last Viewed At */
            last_viewed_at?: string | null;
            /**
             * View Count
             * @default 0
             */
            view_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Heartbeat */
        Heartbeat: {
            /**
             * State
             * @enum {string}
             */
            state: "active" | "quiet" | "dormant" | "closed";
            /** Last Activity At */
            last_activity_at?: string | null;
            last_movement?: components["schemas"]["Movement"] | null;
            stage?: components["schemas"]["StageShare"] | null;
            /** Recent Movement */
            recent_movement?: components["schemas"]["Movement"][];
        };
        /** Injury */
        Injury: {
            /** Name */
            name: string;
            /** Body Region */
            body_region?: string | null;
            /** Severity Tier */
            severity_tier?: ("soft_tissue" | "objective" | "surgical") | null;
            /**
             * Primary
             * @default false
             */
            primary: boolean;
            /** Description */
            description?: string | null;
            /** Citations */
            citations: components["schemas"]["Citation"][];
        };
        /** InviteAcceptRequest */
        InviteAcceptRequest: {
            /** Password */
            password: string;
            /** Name */
            name?: string | null;
        };
        /** KeyMoment */
        KeyMoment: {
            /** Rank */
            rank: number;
            /** Date */
            date?: string | null;
            /** Title */
            title: string;
            /** Importance */
            importance: number;
            /** Rank Reason */
            rank_reason: string;
            /** Citations */
            citations: components["schemas"]["Citation"][];
        };
        /** LastActivity */
        LastActivity: {
            /** At */
            at: string;
            /** Description */
            description: string;
            /** Citations */
            citations: components["schemas"]["Citation"][];
        };
        /** LocateRequest */
        LocateRequest: {
            /** Text */
            text: string;
        };
        /** LocateResult */
        LocateResult: {
            /** Supported */
            supported: boolean;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /** Explanation */
            explanation: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MatterCost */
        MatterCost: {
            /** Matter Id */
            matter_id: number;
            /** Display Number */
            display_number?: string | null;
            /** Description */
            description?: string | null;
            /** Total Usd */
            total_usd: number;
        };
        /** MatterSummary */
        MatterSummary: {
            /** Id */
            id: number;
            /** Display Number */
            display_number?: string | null;
            /** Description */
            description?: string | null;
            /** Status */
            status?: string | null;
            /** Stage */
            stage?: string | null;
            /** Client Name */
            client_name?: string | null;
            /** Last Activity At */
            last_activity_at?: string | null;
        };
        /** MonthAmount */
        MonthAmount: {
            /** Month */
            month: string;
            /** Amount */
            amount: number;
        };
        /** Movement */
        Movement: {
            /** Date */
            date: string;
            /** Text */
            text: string;
        };
        /** NotFound */
        NotFound: {
            /**
             * Not Found
             * @default true
             * @constant
             */
            not_found: true;
            /**
             * Label
             * @description What was looked for, e.g. "UM/UIM limits". UI renders "not found in file".
             */
            label: string;
        };
        /** OkResponse */
        OkResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Message */
            message?: string | null;
        };
        /** OtherCare */
        OtherCare: {
            /** Provider Name */
            provider_name: string;
            /** First Visit */
            first_visit?: string | null;
            /** Last Visit */
            last_visit?: string | null;
        };
        /** Overview */
        Overview: {
            matter: components["schemas"]["MatterSummary"];
            client: components["schemas"]["ClientInfo"];
            stage: components["schemas"]["StageInfo"];
            /** Date Of Incident */
            date_of_incident: components["schemas"]["Cited_str_"] | components["schemas"]["NotFound"];
            /** Statute Of Limitations */
            statute_of_limitations: components["schemas"]["Cited_str_"] | components["schemas"]["NotFound"];
            /** Firm Spend */
            firm_spend: components["schemas"]["Cited_float_"] | components["schemas"]["NotFound"];
            /** Medical Specials */
            medical_specials: components["schemas"]["Cited_float_"] | components["schemas"]["NotFound"];
            next_deadline?: components["schemas"]["DeadlineItem"] | null;
            /** Last Client Contact */
            last_client_contact: components["schemas"]["Cited_ClientContact_"] | components["schemas"]["NotFound"];
            /** Last Synced At */
            last_synced_at?: string | null;
            /** Last Digested At */
            last_digested_at?: string | null;
        };
        /** PolicyVersionDiff */
        PolicyVersionDiff: {
            policy: components["schemas"]["SharePolicy"];
            /** Added */
            added: string[];
            /** Removed */
            removed: string[];
        };
        /** ProviderBills */
        ProviderBills: {
            /** Billed */
            billed: number;
            /** Balance */
            balance?: number | null;
            /**
             * Lien
             * @default false
             */
            lien: boolean;
            /** Items */
            items?: components["schemas"]["BillLine"][];
        };
        /**
         * ProviderCase
         * @description Provider view. Sections not granted by the latest policy are None and MUST be excluded from JSON.
         */
        ProviderCase: {
            /** Grant Id */
            grant_id: number;
            /** Policy Version */
            policy_version: number;
            /** Patient Display */
            patient_display: string;
            /** Firm Name */
            firm_name: string;
            /** Shared By */
            shared_by?: string | null;
            /** Updated At */
            updated_at?: string | null;
            heartbeat?: components["schemas"]["Heartbeat"] | null;
            /** Status Note */
            status_note?: string | null;
            coverage?: components["schemas"]["CoverageShare"] | null;
            case_value?: components["schemas"]["CaseValueShare"] | null;
            bills?: components["schemas"]["ProviderBills"] | null;
            /** Requests */
            requests?: components["schemas"]["ProviderRequest"][] | null;
            /** Documents */
            documents?: components["schemas"]["SharedDocument"][] | null;
            adherence?: components["schemas"]["Adherence"] | null;
            /** Other Care */
            other_care?: components["schemas"]["OtherCare"][] | null;
        };
        /** ProviderCaseSummary */
        ProviderCaseSummary: {
            /** Grant Id */
            grant_id: number;
            /** Patient Display */
            patient_display: string;
            /** Firm Name */
            firm_name: string;
            /** State */
            state?: ("active" | "quiet" | "dormant" | "closed") | null;
            /** Last Movement At */
            last_movement_at?: string | null;
            /**
             * Open Requests
             * @default 0
             */
            open_requests: number;
        };
        /** ProviderDraft */
        ProviderDraft: {
            /** Draft */
            draft: string;
            /** Flags */
            flags: components["schemas"]["DraftFlag"][];
        };
        /** ProviderDraftRequest */
        ProviderDraftRequest: {
            /** Provider Contact Id */
            provider_contact_id: number;
            /** Fields */
            fields: ("status" | "coverage" | "case_value" | "bills" | "open_requests" | "documents" | "adherence" | "other_care")[];
        };
        /** ProviderIdentity */
        ProviderIdentity: {
            /** Contact Id */
            contact_id: number;
            /** Name */
            name: string;
            /** Email */
            email?: string | null;
        };
        /** ProviderRequest */
        ProviderRequest: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "records" | "bills" | "authorization" | "other";
            /** Description */
            description: string;
            /** Requested At */
            requested_at?: string | null;
            /** Channel */
            channel?: string | null;
            /**
             * State
             * @default open
             * @enum {string}
             */
            state: "open" | "completed" | "dismissed";
            /** Provider Contact Id */
            provider_contact_id?: number | null;
            /**
             * Citations
             * @description Always populated for attorneys; for providers only if the source was addressed to them
             */
            citations?: components["schemas"]["Citation"][];
        };
        /** ProviderSummary */
        ProviderSummary: {
            /** Contact Id */
            contact_id: number;
            /** Name */
            name: string;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Relationship */
            relationship?: string | null;
            /** Billed */
            billed: components["schemas"]["Cited_float_"] | components["schemas"]["NotFound"];
            /** Balance */
            balance: components["schemas"]["Cited_float_"] | components["schemas"]["NotFound"];
            /**
             * Lien
             * @default false
             */
            lien: boolean;
            /** Visits */
            visits?: components["schemas"]["Visit"][];
            /** First Visit */
            first_visit?: string | null;
            /** Last Visit */
            last_visit?: string | null;
            /** Current Gap Days */
            current_gap_days?: number | null;
            /** Longest Gap Days */
            longest_gap_days?: number | null;
            /**
             * Open Requests
             * @default 0
             */
            open_requests: number;
        };
        /** Providers */
        Providers: {
            /** Providers */
            providers: components["schemas"]["ProviderSummary"][];
        };
        /** PurposeCost */
        PurposeCost: {
            /** Key */
            key: string;
            /** Usd */
            usd: number;
            /** Calls */
            calls: number;
        };
        /** ReleaseRequest */
        ReleaseRequest: {
            /** Fields */
            fields: ("status" | "coverage" | "case_value" | "bills" | "open_requests" | "documents" | "adherence" | "other_care")[];
            /** Document Ids */
            document_ids?: string[];
            /**
             * Coverage Detail
             * @default confirmed
             * @enum {string}
             */
            coverage_detail: "confirmed" | "limits";
            /** Status Note */
            status_note?: string | null;
        };
        /** ReleaseResult */
        ReleaseResult: {
            policy: components["schemas"]["SharePolicy"];
            /**
             * Invite Url
             * @description Set when an invite was created (also printed to the server console)
             */
            invite_url?: string | null;
        };
        /** ShareAudit */
        ShareAudit: {
            grant: components["schemas"]["Grant"];
            /** Versions */
            versions: components["schemas"]["PolicyVersionDiff"][];
            /** Events */
            events: components["schemas"]["ShareEvent"][];
        };
        /**
         * ShareCandidates
         * @description Everything this provider COULD see, already scoped to them. The composer preview filters it client-side.
         */
        ShareCandidates: {
            provider: components["schemas"]["ProviderIdentity"];
            /** @description All sections populated (coverage per coverage_variants) */
            case: components["schemas"]["ProviderCase"];
            /**
             * Coverage Variants
             * @description {"confirmed": ..., "limits": ...}
             */
            coverage_variants: {
                [key: string]: components["schemas"]["CoverageShare"];
            };
            /** Available Documents */
            available_documents: components["schemas"]["SharedDocument"][];
        };
        /** ShareEvent */
        ShareEvent: {
            /** Id */
            id: number;
            /** Grant Id */
            grant_id: number;
            /** Policy Version */
            policy_version?: number | null;
            /**
             * Event
             * @enum {string}
             */
            event: "released" | "viewed" | "document_opened" | "request_completed" | "request_dismissed" | "revoked" | "invite_sent" | "invite_accepted";
            /** Actor Email */
            actor_email?: string | null;
            /** At */
            at: string;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** SharePolicy */
        SharePolicy: {
            /** Grant Id */
            grant_id: number;
            /** Version */
            version: number;
            /** Fields */
            fields: ("status" | "coverage" | "case_value" | "bills" | "open_requests" | "documents" | "adherence" | "other_care")[];
            /** Document Ids */
            document_ids: string[];
            /**
             * Coverage Detail
             * @enum {string}
             */
            coverage_detail: "confirmed" | "limits";
            /** Status Note */
            status_note?: string | null;
            /** Released By */
            released_by?: string | null;
            /** Released At */
            released_at: string;
        };
        /** SharedDocument */
        SharedDocument: {
            /**
             * Id
             * @description records.id of the document
             */
            id: string;
            /** Title */
            title: string;
            /** Shared At */
            shared_at?: string | null;
            /** Page Count */
            page_count?: number | null;
        };
        /** SourceRecord */
        SourceRecord: {
            /** Record Id */
            record_id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "note" | "communication" | "task" | "calendar_entry" | "document" | "expense" | "time_entry" | "bill" | "medical_record" | "medical_bill" | "damage" | "custom_field" | "matter_event" | "contact";
            /** Title */
            title: string;
            /** Author */
            author?: string | null;
            /** Occurred At */
            occurred_at?: string | null;
            /**
             * Body Text
             * @description Full text; citation offsets without a page index into this
             */
            body_text: string;
            /** Participants */
            participants?: {
                [key: string]: unknown;
            }[];
            /**
             * Page Count
             * @description Set for documents; fetch pages separately
             */
            page_count?: number | null;
            /** Clio Url */
            clio_url?: string | null;
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /** StageInfo */
        StageInfo: {
            /** Current */
            current?: string | null;
            /**
             * Stages
             * @description Ordered stage names for this practice area
             */
            stages?: string[];
            /** Index */
            index?: number | null;
        };
        /** StageShare */
        StageShare: {
            /** Current */
            current?: string | null;
            /** Stages */
            stages?: string[];
            /** Index */
            index?: number | null;
        };
        /** SuggestedQuestions */
        SuggestedQuestions: {
            /** Questions */
            questions: string[];
        };
        /** SyncResult */
        SyncResult: {
            /** Matter Id */
            matter_id: number;
            /** Started At */
            started_at: string;
            /** Finished At */
            finished_at: string;
            /**
             * Counts
             * @description items pulled per Clio resource
             */
            counts: {
                [key: string]: number;
            };
            /** New */
            new: number;
            /** Changed */
            changed: number;
            /** Removed */
            removed: number;
        };
        /** SyncStatus */
        SyncStatus: {
            /** Connected */
            connected: boolean;
            /** Clio User */
            clio_user?: string | null;
            /** Last Synced At */
            last_synced_at?: string | null;
            /**
             * Matters
             * @default 0
             */
            matters: number;
        };
        /** Timeline */
        Timeline: {
            /** Items */
            items: components["schemas"]["TimelineItem"][];
            /** Total */
            total: number;
        };
        /** TimelineItem */
        TimelineItem: {
            /** Record Id */
            record_id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "note" | "communication" | "task" | "calendar_entry" | "document" | "expense" | "time_entry" | "bill" | "medical_record" | "medical_bill" | "damage" | "custom_field" | "matter_event" | "contact";
            /** Title */
            title: string;
            /** Occurred At */
            occurred_at?: string | null;
            /** Author */
            author?: string | null;
            /** One Liner */
            one_liner?: string | null;
            /** Category */
            category?: string | null;
            /** Importance */
            importance?: number | null;
            /** Citations */
            citations: components["schemas"]["Citation"][];
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Name */
            name?: string | null;
            /**
             * Role
             * @enum {string}
             */
            role: "attorney" | "provider";
            /** Provider Contact Id */
            provider_contact_id?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Visit */
        Visit: {
            /** Date */
            date: string;
            /** Description */
            description?: string | null;
            /** Citations */
            citations: components["schemas"]["Citation"][];
        };
        /** VisitResponse */
        VisitResponse: {
            /** Visit Id */
            visit_id: number;
            /** Visited At */
            visited_at: string;
            /**
             * Previous Visit At
             * @description Baseline for /changes; null on first visit
             */
            previous_visit_at?: string | null;
            /** First Visit */
            first_visit: boolean;
            /**
             * Synced
             * @description True if a fresh incremental Clio sync ran before this response
             */
            synced: boolean;
        };
        /** WorthEstimate */
        WorthEstimate: {
            /**
             * Label
             * @default Estimate
             * @constant
             */
            label: "Estimate";
            /** Low */
            low: number;
            /** High */
            high: number;
            /**
             * Currency
             * @default USD
             */
            currency: string;
            /** Assumptions */
            assumptions: components["schemas"]["Assumption"][];
            /** Cap Note */
            cap_note?: string | null;
            /**
             * Method
             * @description Plain-language description of the deterministic method
             */
            method: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ask_api_matters__matter_id__ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description SSE stream, see module doc */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    locate_api_matters__matter_id__locate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocateResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provider_draft_api_matters__matter_id__provider_draft_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderDraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderDraft"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    accept_invite_api_auth_invite__code__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteAcceptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    brief_api_matters__matter_id__brief_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Brief"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    visit_api_matters__matter_id__visits_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    changes_api_matters__matter_id__changes_get: {
        parameters: {
            query?: {
                since?: string | null;
            };
            header?: never;
            path: {
                matter_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Changes"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delta_api_matters__matter_id__delta_get: {
        parameters: {
            query?: {
                since?: string | null;
            };
            header?: never;
            path: {
                matter_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Delta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggested_questions_api_matters__matter_id__suggested_questions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestedQuestions"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    matter_costs_api_ai_costs_get: {
        parameters: {
            query?: {
                matter_id?: number | null;
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiCostReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    firm_costs_api_ai_costs_firm_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FirmCostReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_digest_api_digest__matter_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    digest_runs_api_matters__matter_id__digest_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DigestRun"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_matters_api_matters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatterSummary"][];
                };
            };
        };
    };
    overview_api_matters__matter_id__overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    timeline_api_matters__matter_id__timeline_get: {
        parameters: {
            query?: {
                types?: string | null;
                since?: string | null;
                q?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                matter_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeline"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deadlines_api_matters__matter_id__deadlines_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deadlines"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    costs_api_matters__matter_id__costs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Costs"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    providers_api_matters__matter_id__providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Providers"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_cases_api_provider_cases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderCaseSummary"][];
                };
            };
        };
    };
    my_case_api_provider_cases__grant_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                grant_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderCase"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_document_api_provider_cases__grant_id__documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                grant_id: number;
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_request_api_provider_requests__request_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_record_api_records__record_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_page_api_documents__document_id__pages__page_no__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
                page_no: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_page_image_api_documents__document_id__pages__page_no__image_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
                page_no: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_file_api_documents__document_id__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    share_candidates_api_matters__matter_id__share_candidates_get: {
        parameters: {
            query: {
                provider_contact_id: number;
            };
            header?: never;
            path: {
                matter_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareCandidates"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_grants_api_matters__matter_id__shares_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Grant"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_grant_api_shares_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGrantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Grant"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    release_api_shares__grant_id__release_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                grant_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReleaseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_api_shares__grant_id__revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                grant_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_api_shares__grant_id__audit_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                grant_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareAudit"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismiss_request_api_requests__request_id__dismiss_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clio_login_auth_clio_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    clio_callback_auth_clio_callback_get: {
        parameters: {
            query?: {
                code?: string | null;
                state?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_matter_api_sync__matter_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matter_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_status_api_sync_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatus"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
